# More difficult to understand but more compact way would be to take all arguments of print, put them into a list, and as self.turns increases, keep printing the required elements of the list onto the screen. Easier to understand method is used here:

def image(self):
	if self.turns == 8:
		print('  ____')
		print(' |')
		print(' |')
		print(' |')
		print(' |')
		print(' |')
		print(' |')
	elif self.turns == 7:
		print('  ____')
		print(' |')
		print(' |    O')
		print(' |')
		print(' |')
		print(' |')
		print(' |')
	elif self.turns == 6:
		print('  ____')
		print(' |')
		print(' |    O')
		print(' |    |')
		print(' |')
		print(' |')
		print(' |')
	elif self.turns == 5:
		print('  ____')
		print(' |')
		print(' |    O')
		print(' |   /|')
		print(' |')
		print(' |')
		print(' |')
	elif self.turns == 4:
		print('  ____')
		print(' |')
		print(' |    O')
		print(' |   /|\ ')
		print(' |')
		print(' |')
		print(' |')
	elif self.turns == 3:
		print('  ____')
		print(' |')
		print(' |    O')
		print(' |   /|\ ')
		print(' |    |')
		print(' |')
		print(' |')
	elif self.turns == 2:
		print('  ____')
		print(' |')
		print(' |    O')
		print(' |   /|\ ')
		print(' |    |')
		print(' |   /')
		print(' |')
	elif self.turns == 1:
		print('  ____')
		print(' |')
		print(' |    O')
		print(' |   /|\ ')
		print(' |    |')
		print(' |   / \ ')
		print(' |')
	else:
		print('  ____')
		print(' |    |')
		print(' |    O')
		print(' |   /|\ ')
		print(' |    |')
		print(' |   / \ ')
		print(' |')